[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "EvoX1"
authors = [{name = "Lai Jun Kang", email = "junkanglai93@gmail.com"}]
dynamic = ["version", "description"]
