[evo_common]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
    symlink://../..
build_flags =
    -std=gnu++17
    -DARDUINO_USB_CDC_ON_BOOT=1
build_unflags =
    -std=gnu++11

[env:EVO_X1E]
extends = evo_common
board = esp32-s3-devkitm-1
build_flags =
    ${evo_common.build_flags}
    -DEVO_BOARD_X1E

[env:EVO_X1P]
extends = evo_common
board = esp32-s3-devkitm-1
build_flags =
    ${evo_common.build_flags}
    -DEVO_BOARD_X1P
